#!/bin/bash

CFG_DIR=/var/vcap/jobs/haproxy/config
RUN_DIR=/var/vcap/sys/run/haproxy
LOG_DIR=/var/vcap/sys/log/haproxy

PIDFILE=$RUN_DIR/haproxy.pid
RUNAS=vcap

function pid_exists() {
  ps -p $1 &> /dev/null
}

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $CFG_DIR $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    exec chpst -u $RUNAS:$RUNAS \
      /var/vcap/jobs/haproxy/packages/haproxy/haproxy-1.6.5/haproxy -f $CFG_DIR/haproxy.conf -D -p "$PIDFILE"
    >>$LOG_DIR/server.stdout.log 2>>$LOG_DIR/server.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: ctl {start|stop|console}" ;;
esac
exit 0
